<li class="xwdt1" data-scroll-reveal=" enter left and move 100px over 1.33s "><a href="[field:arcurl/]">
        <div class="xwdt1_left">
          <h4>[field:fulltitle/]</h4>
          <p>[field:infos/]...</p>
          <p class="xwdt1_left_clolr">MORE+</p>
        </div>
        <div class="xwdt1_right">
          <p class="xwdt1_right_sj">[field:pubdate function=MyDate('d',@me)/]</p>
          <p>[field:pubdate function=MyDate('Y-m',@me)/]</p>
        </div>
        </a> </li>