<?php
$z[0]=Array("global","",112,138);
$z[0][4]=array();
$z[0][4]['name']="cfg_company";
$z[1]=Array("field","",209,265);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['function']="IndexCurrent(@me,'sele')";
$z[2]=Array("channelartlist","	\r\n        <li class=\"{dede:field.currentstyle/}\"><a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n          <ol>\r\n          {dede:channel type=\"son\"}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n          </ol>\r\n        </li>\r\n",306,673);
$z[2][4]=array();
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="sele";
$z[3]=Array("global","",825,851);
$z[3][4]=array();
$z[3][4]['name']="cfg_company";
$z[4]=Array("channelartlist","\r\n      <li ><a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n          <ol>\r\n          {dede:channel type=\"son\"}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n          </ol>\r\n        </li>\r\n",966,1276);
$z[4][4]=array();
$z[4][4]['typeid']="top";

?>