<?php
$z[0]=Array("global","",168,194);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",289,316);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",356,386);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",604,639);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n    <li data-scroll-reveal=\" enter bottom and move 100px over 1.33s \"> <a href=\"[field:arcurl/]\">\r\n      <div class=\"imgbox\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\"/> </div>\r\n      <p>[field:title/]</p>\r\n      <div class=\"hover\"> <b></b>\r\n        <div class=\"txt\"> <span>查看详情</span> </div>\r\n      </div>\r\n      </a> </li>\r\n",2375,2761);
$z[4][4]=array();
$z[4][4]['typeid']="8";
$z[4][4]['row']="5";
$z[5]=Array("arclist","\r\n      <li class=\"xwdt1\" data-scroll-reveal=\" enter left and move 100px over 1.33s \"><a href=\"[field:arcurl/]\">\r\n        <div class=\"xwdt1_left\">\r\n          <h4>[field:fulltitle/]</h4>\r\n          <p>[field:infos/]...</p>\r\n          <p class=\"xwdt1_left_clolr\">MORE+</p>\r\n        </div>\r\n        <div class=\"xwdt1_right\">\r\n          <p class=\"xwdt1_right_sj\">[field:pubdate function=MyDate('d',@me)/]</p>\r\n          <p>[field:pubdate function=MyDate('Y-m',@me)/]</p>\r\n        </div>\r\n        </a> </li>\r\n",4553,5113);
$z[5][4]=array();
$z[5][4]['row']="6";
$z[5][4]['typeid']="5";
$z[5][4]['infolen']="140";
$z[6]=Array("include","",5145,5182);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>