<?php
$z[0]=Array("field","",168,187);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",190,216);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",311,365);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[2][4]['function']="dede97_keywords(@me)";
$z[3]=Array("field","",405,465);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="dede97_description(@me)";
$z[4]=Array("include","",683,718);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",893,915);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n    <li class=\"cp_show_top_2 \"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n  ",992,1215);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='cp_show_top_2'><a class='on' href='~typelink~'>~typename~</a></li>";
$z[7]=Array("list","\r\n      <li class=\"xw_dt1\" data-scroll-reveal=\" enter left and move 100px over 1.33s \"><a href=\"[field:arcurl/]\">\r\n        <div class=\"xw_dt1_left\">\r\n          <h4>[field:fulltitle/]</h4>\r\n          <p>[field:infos/]...</p>\r\n          <p class=\"xw_dt1_left_clolr\">MORE+</p>\r\n        </div>\r\n        <div class=\"xw_dt1_right\">\r\n          <p class=\"xw_dt1_right_sj\">[field:pubdate function=MyDate('d',@me)/]</p>\r\n          <p>[field:pubdate function=MyDate('Y-m',@me)/]</p>\r\n        </div>\r\n        </a> </li>\r\n  ",1323,1869);
$z[7][4]=array();
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1979,2047);
$z[8][4]=array();
$z[8][4]['listitem']="index,pre,next,pageno,end,";
$z[8][4]['listsize']="3";
$z[9]=Array("include","",2066,2103);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>