INSERT INTO `#@__admintype` VALUES('1','信息发布员','1','t_AccList a_AccNew a_AccList a_MyList a_MyEdit a_MyDel sys_MdPwd sys_Feedback sys_MyUpload plus_留言簿模块 '),
('5','频道管理员','1','t_AccList t_AccNew t_AccEdit t_AccDel a_AccNew a_AccList a_AccEdit a_AccDel a_AccCheck a_MyList a_MyEdit a_MyDel a_MyCheck co_AddNote co_EditNote co_PlayNote co_ListNote co_ViewNote spec_New spec_List spec_Edit sys_MdPwd sys_Log sys_ArcTj sys_Source sys_Writer sys_Keyword sys_MakeHtml sys_Feedback sys_Upload sys_MyUpload member_List member_Edit plus_站内新闻发布 plus_友情链接模块 plus_留言簿模块 plus_投票模块 plus_广告管理 '),
('10','超级管理员','1','admin_AllowAll ');
INSERT INTO `#@__arcatt` VALUES('5','s','滚动'),
('1','h','头条'),
('3','f','幻灯'),
('2','c','推荐'),
('7','p','图片'),
('8','j','跳转'),
('4','a','特荐'),
('6','b','加粗');
INSERT INTO `#@__arcrank` VALUES('1','0','开放浏览','5','0','0',''),
('2','-1','待审核稿件','0','0','0','');
INSERT INTO `#@__channeltype` VALUES('1','article','普通文章','#@__archives','#@__addonarticle','article_add.php','content_list.php','article_edit.php','article_add.php','content_list.php','article_edit.php','<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">\t\n</field:body>\t\n','','','1','1','1','-1','','10','0','1','1','标题','0','0'),
('2','image','图集文章','#@__archives','#@__addonimages','album_add.php','content_i_list.php','album_edit.php','album_add.php','content_list.php','album_edit.php','<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />\t\n<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>\t\n<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>','','','1','1','1','-1','','10','0','1','1','标题','0','0');
INSERT INTO `#@__flink` VALUES('1','1','http://dede97.com','织梦97','','','','1226375403','1','2'),
('2','1','http://dede97.com','织梦模板','','','','1226375403','1','2');
INSERT INTO `#@__flinktype` VALUES('1','综合网站'),
('2','娱乐类'),
('3','教育类'),
('4','计算机类'),
('5','电子商务'),
('6','网上信息'),
('7','论坛类'),
('8','其它类型');
INSERT INTO `#@__homepageset` VALUES('default/index.htm','../index.html','1');
INSERT INTO `#@__sysconfig` VALUES('1','cfg_basehost','站点根网址（保存后自动采集记录）','1','string',''),
('2','cfg_indexurl','主页链接（保存后自动采集记录）','1','string','/'),
('3','cfg_indexname','主页链接名','1','string','主页'),
('4','cfg_arcdir','文档HTML默认保存路径','1','string','/html'),
('5','cfg_df_style','模板所在目录','1','string','default'),
('6','cfg_webname','网站名称','1','string','DEDE97.织梦97模板建站'),
('7','cfg_keywords','站点默认关键字','1','string','关键词'),
('8','cfg_description','站点描述','1','bstring','网站描述'),
('9','cfg_beian','网站备案号','1','string','京ICP备888xxx88'),
('10','cfg_powerby','网站版权信息','1','bstring','Copyright &copy; 2018 DEDE97. 织梦97 版权所有'),
('11','cfg_company','公司名称','1','string','极速递（廊坊）网络科技有限公司'),
('12','cfg_tel','联系电话','1','string','400xxx8888'),
('13','cfg_mobile','手机号码','1','string','136xxx98888'),
('14','cfg_qq','QQ号码','1','string','282140068'),
('15','cfg_email','电子邮箱','1','string','service@dede97.com'),
('16','cfg_address','联系地址','1','string','北京市朝阳区国贸大厦A8888'),
('17','cfg_fax','传真号码','1','string','010-8888xxxx'),
('20','cfg_cmspath','安装目录（保存后自动采集记录）','2','string',''),
('21','cfg_cookie_encode','cookie加密码','2','string','302f360a0a4b1be2f8d6f85be2c9'),
('23','cfg_html_editor','Html编辑器（推荐kindeditor,可选ckeditor）','2','string','kindeditor'),
('24','cfg_fck_xhtml','编辑器(是/否)使用XHTML','2','bool','N'),
('25','cfg_list_symbol','栏目位置的间隔符号','2','string',' &#62; '),
('26','cfg_keyword_replace','关键字替换(是/否)使用本功能会影响HTML生成速度','2','bool','N'),
('27','cfg_multi_site','(是/否)支持多站点，开启此项后附件、栏目连接、arclist内容启用绝对网址','2','bool','N'),
('28','cfg_dede_log','(是/否)开启管理日志','2','bool','N'),
('29','cfg_cli_time','服务器时区设置','2','number','8'),
('37','cfg_upload_switch','删除文章文件同时删除相关附件文件','2','bool','N'),
('38','cfg_allsearch_limit','网站全局搜索时间限制','2','string','5'),
('39','cfg_rewrite','是否使用伪静态','2','bool','N'),
('40','cfg_delete','文章回收站(是/否)开启','2','bool','Y'),
('41','cfg_mysql_type','数据库类型（推荐mysqli，可选mysql）','2','string','mysqli'),
('50','cfg_medias_dir','图片/上传文件默认路径','3','string','/uploads'),
('51','cfg_ddimg_width','缩略图默认宽度','3','number','240'),
('52','cfg_ddimg_height','缩略图默认高度','3','number','180'),
('53','cfg_imgtype','图片浏览器文件类型','3','string','jpg|gif|png'),
('54','cfg_softtype','允许上传的软件类型','3','string','zip|gz|rar|iso|doc|xsl|ppt|wps'),
('55','cfg_mediatype','允许的多媒体文件类型','3','string','swf|mpg|mp3|rm|rmvb|wmv|wma|wav|mid|mov'),
('56','cfg_album_width','图集默认显示图片的大小','3','number','800'),
('57','cfg_album_row','图集多行多列样式默认行数','3','number','3'),
('58','cfg_album_col','图集多行多列样式默认列数','3','number','4'),
('59','cfg_album_pagesize','图集多页多图每页显示最大数','3','number','12'),
('60','cfg_album_style','图集默认样式<br />1为多页多图,2为多页单图,3为缩略图列表','3','number','2'),
('61','cfg_album_ddwidth','图集默认缩略图大小','3','number','200'),
('62','cfg_addon_savetype','附件保存形式(按data函数日期参数)','3','string','ymd'),
('63','cfg_qk_uploadlit','异步上传缩略图(空间太不稳定的用户关闭此项)','3','bool','Y'),
('64','cfg_ddimg_full','自生成的缩略图对背景填充(选否为剪裁)','3','bool','N'),
('65','cfg_ddimg_bgcolor','缩略图空白背景填充颜色(0-白,1-黑)','3','number','0'),
('66','cfg_uplitpic_cut','上传缩略图后是否马上弹出裁剪框','3','bool','N'),
('67','cfg_album_mark','图集是否使用水印(小图也会受影响)','3','bool','N'),
('68','cfg_source_url','源网址(请一定留空除非你懂原理)','3','string',''),
('69','cfg_mb_pwdtype','前台密码验证类型：默认32 — 32位md5，可选：<br />l16 — 前16位， r16 — 后16位， m16 — 中间16位','4','string','32'),
('70','cfg_arcsptitle','(是/否)开启分页标题，开启会影响HTML生成速度','6','bool','N'),
('71','cfg_arcautosp','(是/否)开启长文章自动分页','6','bool','N'),
('72','cfg_arcautosp_size','文章自动分页大小（单位: K）','6','number','5'),
('73','cfg_list_son','上级列表是否包含子类内容','6','bool','Y'),
('74','cfg_keyword_like','使用关键词关连文章','6','bool','N'),
('75','cfg_index_cache','arclist标签调用缓存<br />(0 不启用，大于0值为多少秒)','6','number','8640'),
('76','cfg_tplcache','是否启用模板缓存','6','bool','Y'),
('77','cfg_tplcache_dir','模板缓存目录','6','string','/data/tplcache'),
('78','cfg_makesign_cache','发布/修改单个文档是否使用调用缓存','6','bool','N'),
('79','cfg_search_max','最大搜索检查文档数','6','number','50000'),
('80','cfg_search_maxrc','最大返回搜索结果数','6','number','300'),
('81','cfg_search_time','搜索间隔时间(秒/对网站所有用户)','6','number','6'),
('82','cfg_need_typeid2','是否启用副栏目','6','bool','Y'),
('83','cfg_cache_type','id 文档ID，content 标签最终内容<br />(修改此变量后必须更新系统缓存)','6','string','id'),
('84','cfg_makeindex','发布文章后马上更新网站主页','6','bool','N'),
('85','cfg_make_andcat','发表文章后马上更新相关栏目','6','bool','N'),
('86','cfg_make_prenext','发表文章后马上更新上下篇','6','bool','N'),
('87','cfg_puccache_time','需缓存内容全局缓存时间(秒)','6','number','36000'),
('88','cfg_memcache_enable','是否启用memcache缓存，默认使用文件缓存','6','bool','N'),
('89','cfg_memcache_mc_defa','默认memcache缓存服务器地址','6','string','memcache://127.0.0.1:11211/default127'),
('90','cfg_auot_description','自动摘要长度（0-250，0表示不启用）','7','number','240'),
('91','cfg_rm_remote','远程图片本地化','7','bool','Y'),
('92','cfg_jump_once','跳转网址是否直接跳转？（否则显示中转页）','7','bool','Y'),
('93','cfg_arc_dellink','删除非站内链接','7','bool','Y'),
('94','cfg_arc_autopic','提取第一张图片作为缩略图','7','bool','Y'),
('95','cfg_arc_autokeyword','自动提取关键字','7','bool','Y'),
('96','cfg_title_maxlen','文档标题最大长度<br>改此参数后需要手工修改数据表','7','number','60'),
('97','cfg_check_title','发布文档时是否检测重复标题','7','bool','Y'),
('100','cfg_df_dutyadmin','默认责任编辑(dutyadmin)','7','string','admin'),
('101','cfg_arc_click','文档默认点击数(-1表示随机50-200)','7','number','-1'),
('102','cfg_replace_num','文档内容同一关键词替换次数(0为全部替换)','7','number','2'),
('103','cfg_sphinx_article','是否启用文章全文检索功能（需配置sphinx服务器）','7','bool','N'),
('104','cfg_sphinx_host','Sphinx服务器主机地址','7','string','localhost'),
('105','cfg_sphinx_port','Sphinx服务器端口号','7','number','9312'),
('106','cfg_cross_sectypeid', '支持交叉栏目显示副栏目内容', '7', 'bool', 'N'),
('107','cfg_disable_funs', '模板引擎禁用PHP函数', '7', 'bstring', 'phpinfo,eval,exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source,file_put_contents'),
('108','cfg_disable_tags', '模板引擎禁用标签', '7', 'string', 'php'),
('109','cfg_sys_typeid','系统保留最大栏目ID(避免误删除)','7','number','0');
ALTER TABLE `#@__arctiny` ADD INDEX `idx_typeid_arcrank_sortrank` (`typeid`, `arcrank`, `sortrank`);
